name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest  # Changez ceci à windows-latest ou ubuntu-latest si nécessaire

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python3.8 -m pip install --upgrade pip
        pip install keras pillow numpy tensorflow scipy

    - name: Run training script
      run: |
        python RNA/entrainement.py

    - name: Upload model as artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: RNA/model.h5

  upload_and_commit:
    needs: build
    runs-on: macos-latest  # Changez ceci à windows-latest ou ubuntu-latest si nécessaire

    permissions:
      contents: write  # Ajoutez cette ligne pour donner les permissions d'écriture

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: trained-model
        path: RNA/

    - name: Increase Git buffer size
      run: git config --global http.postBuffer 157286400

    - name: Commit and push model
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Utiliser le jeton GitHub pour l'authentification
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add RNA/model.h5
        git commit -m "Add trained model"
        git remote set-url origin https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git push origin main
