name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest  # Changez ceci à windows-latest ou ubuntu-latest si nécessaire

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install keras pillow numpy tensorflow scipy  # Ajoutez scipy ici

    - name: Run training script
      run: |
        python RNA/entrainement.py
        
    - name: Upload model as artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: RNA/model.h5
