name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python3.8 -m pip install --upgrade pip
        pip install keras pillow numpy tensorflow scipy

    - name: Run training script
      run: |
        python RNA/entrainement.py

    - name: Upload model as artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: RNA/model.h5

  upload_to_drive:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: trained-model
        path: RNA/

    - name: Install gdrive
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget -O gdrive https://github.com/prasmussen/gdrive/releases/download/2.1.0/gdrive-linux-x64
        chmod +x gdrive
        sudo install gdrive /usr/local/bin/gdrive

    - name: Upload model to Google Drive
      env:
        GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
      run: |
        echo "$GDRIVE_CREDENTIALS" > gdrive-service-account.json
        gdrive --service-account gdrive-service-account.json upload RNA/model.h5 --parent 1vRuDW6sRB_jAfH3QWuQQwYcwLjzfpcrg

  download_and_commit:
    needs: upload_to_drive
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install gdrive
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget -O gdrive https://github.com/prasmussen/gdrive/releases/download/2.1.0/gdrive-linux-x64
        chmod +x gdrive
        sudo install gdrive /usr/local/bin/gdrive

    - name: Download model from Google Drive
      env:
        GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
      run: |
        echo "$GDRIVE_CREDENTIALS" > gdrive-service-account.json
        gdrive --service-account gdrive-service-account.json list --query "name contains 'model.h5'" --max 1 --no-header > file_id.txt
        FILE_ID=$(awk '{print $1}' file_id.txt)
        gdrive --service-account gdrive-service-account.json download $FILE_ID --path RNA/

    - name: Commit and push model metadata
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add RNA/model_metadata.txt
        git commit -m "Add model metadata"
        git remote set-url origin https://${{ github.actor }}:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
        git push origin main
